;;; !!! This configuration is handled by HelloImGui and stores several Ini Files, separated by markers like this:
           ;;;<<<INI_NAME>>>;;;

;;;<<<ImGui_655921752_Default>>>;;;
[Window][Debug##Default]
Pos=60,60
Size=400,400
Collapsed=0

[Window][Main]
Pos=0,0
Size=1000,650
Collapsed=0

[Window][Client Config]
Pos=434,274
Size=131,102
Collapsed=0

[Table][0xA07D910C,3]
RefScale=15
Column 0  Width=69
Column 1  Width=99
Column 2  Weight=1.0000

[Docking][Data]

;;;<<<Layout_655921752_Default>>>;;;
;;;<<<HelloImGui_Misc>>>;;;
[Layout]
Name=Default
[StatusBar]
Show=false
ShowFps=true
[Theme]
Name=DarculaDarker
;;;<<<SplitIds>>>;;;
{"gImGuiSplitIDs":{}}
